[package]
name = "backend"
version = "0.1.0"
edition = "2021" # use 2024 only if your rustc supports it

[dependencies]
axum = "0.8.4"
tokio = { version = "1.45.1", features = ["full"] }
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio-native-tls", "macros", "chrono"] }
serde = { version = "1.0.219", features = ["derive"] }
tower-http = { version = "0.6.6", features = ["cors", "fs"] }
argon2 = "0.5.3"
dotenvy = "0.15.7"
thiserror = "2.0.12"
base64 = "0.22.1"
reqwest = { version = "0.12.23", features = ["json"] }
chrono = { version = "0.4.41", features = ["serde"] }
shared = { path = "../shared" }

# Soroban
soroban-client = "0.5.1"
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4"] }

[lib]
name = "backend"
path = "src/lib.rs"

[[bin]]
name = "backend"
path = "src/main.rs"


